---
version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8890:8890"
    depends_on:
      - postgres
      - pgadmin
      - front
  front:
    build:
      dockerfile: Dockerfile
      context: ./frontend/desafio
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - pgadmin
  postgres:
    image: 'postgres:14.5-alpine'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=luke
      - POSTGRES_DB=app    
    ports:
      - "5434:5432"
    volumes:
      - "./backend/data.sql:/docker-entrypoint-initdb.d/data.sql"
    

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres


networks:
  default: